### ISSUE TITLE
Query unbonding amount

### ISSUE THREAD

**Issue by JakeHartnell** [DA0-DA0/cw20-staking#2]
Context: https://github.com/DA0-DA0/cw20-staking/pull/1/files#r737057156

**Comment by ben2x4** [comment]
The query claims msg should return this information. It might be more ergonomic to have more specific queries, but not totally convinced. Queries are free so seem fine to just return all the claim info as most front ends will need it all anyways. https://github.com/DA0-DA0/cw20-staking/blob/8c4939ea72b3d3a1a42b5f89eeec2a57e9c0ffd0/src/contract.rs#L245

**Comment by JakeHartnell** [comment]
> The query claims msg should return this information. It might be more ergonomic to have more specific queries, but not totally convinced. Queries are free so seem fine to just return all the claim info as most front ends will need it all anyways.
> 
> https://github.com/DA0-DA0/cw20-staking/blob/8c4939ea72b3d3a1a42b5f89eeec2a57e9c0ffd0/src/contract.rs#L245

Cool.
